spring:
  application:
    name: rrhh-service
  datasource:
    url: jdbc:oracle:thin:@${ORACLE_HOST:localhost}:${ORACLE_PORT:1521}:${ORACLE_SERVICE:ORCL}
    username: ${ORACLE_USERNAME:sigre_user}
    password: ${ORACLE_PASSWORD:sigre_password}
    driver-class-name: oracle.jdbc.OracleDriver
server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

