spring:
  application:
    name: auditoria-service
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: 27017
      database: sigre_audit
server:
  port: 8097
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

