spring:
  application:
    name: produccion-service
  datasource:
    url: jdbc:oracle:thin:@${ORACLE_HOST:localhost}:${ORACLE_PORT:1521}:${ORACLE_SERVICE:ORCL}
    username: ${ORACLE_USERNAME:sigre_user}
    password: ${ORACLE_PASSWORD:sigre_password}
server:
  port: 8086
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

